#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: ubuntu
    username: "user"
    password: "user"
  keyboard:
    layout: "fr"
  locale: "fr_FR.UTF-8"
  network:
    network:
      version: 2
      ethernets:
        ens33:
          dhcp4: true
  storage:
    layout:
      name: lvm
  updates: security
  user-data:
    packages:
      - curl
      - git
      - ca-certificates
      - gnupg
      - zsh
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - redis-server
      - peek
    runcmd:
      - echo "Installation terminée, configuration des outils..."
      
      # 🌟 Installer Oh My Zsh
      - sudo apt install -y zsh
      - chsh -s $(which zsh) user
      - su - user -c 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'

      # 🌟 Installer les plugins Zsh
      - su - user -c 'git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions'
      - su - user -c 'git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting'
      - su - user -c 'echo "plugins=(git zsh-autosuggestions zsh-syntax-highlighting)" >> ~/.zshrc'
      - su - user -c 'source ~/.zshrc'

      # 🌟 Installer Powerlevel10k
      - su - user -c 'git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes/powerlevel10k'
      - su - user -c 'echo "ZSH_THEME=\"powerlevel10k/powerlevel10k\"" >> ~/.zshrc'
      - su - user -c 'source ~/.zshrc'

      # 🌟 Configurer Git
      - su - user -c 'git config --global user.name "Votre Nom"'
      - su - user -c 'git config --global user.email "votre.email@example.com"'
      - su - user -c 'git config --global core.editor "code --wait"'
      - su - user -c 'git config --global color.ui auto'

      # 🌟 Installer NVM et Node.js
      - su - user -c 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash'
      - su - user -c 'source ~/.zshrc'
      - su - user -c 'nvm install --lts'
      - su - user -c 'nvm alias default node'
      
      # 🌟 Installer Angular CLI et NestJS
      - su - user -c 'npm install -g @angular/cli'
      - su - user -c 'npm install -g @nestjs/cli'

      # 🌟 Installer GitHub CLI
      - curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
      - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
      - sudo apt update
      - sudo apt install -y gh
      - su - user -c 'gh auth login'

      # 🌟 Installer Redis
      - npm install -g redis-cli
      - sudo apt install -y redis-server

      # 🌟 Fin du script
      - echo "Installation terminée avec succès !"
